title: Party Game
description: Українська локальна гра для компанії
lang: uk-UA
theme: jekyll-theme-cayman
show_downloads: false
url: https://vaniawl.github.io
baseurl: /partygame-pages
github:
  is_project_page: false
